### ISSUE TITLE
A-TET-001010 - Drawing update

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/project-tetra#101]
- [x] Reorder parts list, item #10 is missing

**Comment by Judoguy12** [comment]
Should be good now @mechatroniks-git

**Comment by mechatroniks-git** [comment]
There appears to be 2 drawing files for this assembly. 
Remove the trail for the nut that doesn't make sense
You need to clean up the arrows
![image](https://user-images.githubusercontent.com/57600622/88200891-9f6a6000-cbfb-11ea-8fd0-3ad4f309b5b9.png)

**Comment by Judoguy12** [comment]
The trail on that nut can't go to there as fusion is tracking the nut back to where it came from as if it was all moved down at once

**Comment by Judoguy12** [comment]
Done @mechatroniks-git
