### ISSUE TITLE
Organize tickets/ issues to different repos

### ISSUE THREAD

**Issue by professor-nimrod** [tetrabiodistributed/project-tetra#107]
Organize issues and tickets to their respective repos/ boards, which this ticket is ironically contributing to.

**Comment by professor-nimrod** [comment]
Can't assign this to me for some reason right now, but I will take care of it at a point we all agree on

**Comment by Judoguy12** [comment]
Assigned you

**Comment by capsulecorplab** [comment]
PSA: every repo should have its own project board now!

**Comment by Burhan-Q** [comment]
> PSA: every repo should have its own project board now!

@capsulecorplab should this ticket get closed?

**Comment by capsulecorplab** [comment]
Closing!
