### ISSUE TITLE
Sensirion control PCB adjustments

### ISSUE THREAD

**Issue by Burhan-Q** [tetrabiodistributed/project-tetra#113]
Phoenix connector needs to move inboard to avoid issues with mounting to Sensirion sensor.
Needed for Issue #67 

### Current distance (center to center):
Phoenix pins to pogo pins = 9.705mm
Phoenix pins to board face = 6.721mm

### Constraints:
Distance pogo pins to front of sensirion cut out = 9.597mm - 0.862mm = 8.735mm [bumpouts on inside of Sensirion cutout]
Phoenix connector to control board PCB component = 1.938mm (max distance phoenix connector can move backwards, see image below)

#### Image of interference
![image](https://user-images.githubusercontent.com/62214284/89218241-b44fd780-d59b-11ea-99b5-748f81f3100b.png)

#### Pogo pins to front wall (subtract 0.862mm for bump-out, center to edge)
![image](https://user-images.githubusercontent.com/62214284/89218291-c7fb3e00-d59b-11ea-9f68-b82b63103e69.png)

#### Current space between pogo pins and phoenix connector pins (center to center)
![image](https://user-images.githubusercontent.com/62214284/89218336-dd706800-d59b-11ea-845b-b031c3d8d267.png)

#### Current phoenix pins to board (center to face):
![image](https://user-images.githubusercontent.com/62214284/89218523-30e2b600-d59c-11ea-8c82-60956fd7bf48.png)

#### Phoenix pins to Sensirion PCB component:
![image](https://user-images.githubusercontent.com/62214284/89218673-756e5180-d59c-11ea-8b3b-edbc9055be32.png)

#### Second view:
![image](https://user-images.githubusercontent.com/62214284/89218738-933bb680-d59c-11ea-8972-14eb64b94d8c.png)

#### Space between rear of (current) phoenix connector to control board PCB component:
![image](https://user-images.githubusercontent.com/62214284/89218844-bfefce00-d59c-11ea-9e3a-0a07355f93f2.png)

**Comment by Burhan-Q** [comment]
Uploaded these to Slack, but also posting them here
[STEP_files_requested.zip](https://github.com/tetrabiodistributed/project-tetra/files/5018030/STEP_files_requested.zip)

**Comment by Burhan-Q** [comment]
### Pogo pins and phoenix connector pins
Center to center distance on @mechatroniks-git board model = 8.43mm
![image](https://user-images.githubusercontent.com/62214284/89219354-9d11e980-d59d-11ea-88a5-67277ae087ab.png)

### Phoenix connector pins to board face
Center to face distance = 8.00mm
![image](https://user-images.githubusercontent.com/62214284/89219539-f2e69180-d59d-11ea-9514-66ed4b64c2c1.png)

**Comment by hydronics2** [comment]
@Burhan-Q ... created a pull request with the new files. thanks for the pics!... and that fusion 360 model is worth a 1000 words.
