### ISSUE TITLE
Software compliance

### ISSUE THREAD

**Issue by Judoguy12** [tetrabiodistributed/project-tetra#12]
The UK standard says that all safety critical software (which this probably would be) must comply with a standard call 62304. Do we know if the team is working to this standard?
Link here https://www.iso.org/standard/38421.html

**Comment by fpdotmonkey** [comment]
We aimed for AAMI 50501, which I believe is a COVID EUA version of that standard

**Comment by Judoguy12** [comment]
Ok perfect
