### ISSUE TITLE
Pi Hat design updates

### ISSUE THREAD

**Issue by fpdotmonkey** [tetrabiodistributed/project-tetra#129]
- [ ] Hardware Port 1 for the Sensirion Sensor should correspond to software port 0
- [ ] The 50-pin connector to the Pi shouldn't allow for pins to be off by 1
- [x] The silkscreen for the buzzer should indicate which side is positive
- [x] There should be an interface for the software to hard reset the sensor

**Comment by hydronics2** [comment]
- added a p-channel mosfet and transistor circuit to cycle power to all the sensirion flow sensors
- removed the buzzer per request as it is an alarm that we don't have regulatory permissions to indicate
https://github.com/tetrabiodistributed/project-tetra/pull/135

**Comment by mechatroniks-git** [comment]
The request for the logical ports (starting at 0) to align with physical pin numbers (starting at 1) is not recommended practice, as all the datasheets have pins that start at pin 1. The hardware should reference the datasheet. 

If the request was to align GPIO ports, then best to maintain a config.h with the hardware mappings.
