### ISSUE TITLE
I2C address selection pins not connected in accordance with application note

### ISSUE THREAD

**Issue by darraghbr** [tetrabiodistributed/project-tetra#148]
The I2C address selection pins on the I2C multiplexer are currently connected to GND or 3.3V via a 10K resistor, the application note suggests that they are connected directly to 3.3V or GND, this is probably not critical.

On the schematic this applies to R19, 20, 25 and R39-41.

**Comment by mechatroniks-git** [comment]
On page 5&6 of [datasheet](https://www.ti.com/lit/ds/symlink/tca9548a.pdf?ts=1607713427169&ref_url=https%253A%252F%252Fwww.ti.com%252Fstore%252Fti%252Fen%252Fp%252Fproduct%252F%253Fp%253DTCA9548APWR)

![image](https://user-images.githubusercontent.com/57600622/101990861-c59da480-3c5d-11eb-802e-87736a6de68b.png)


![image](https://user-images.githubusercontent.com/57600622/101990632-c7b33380-3c5c-11eb-85aa-b7d8033f998e.png)

shows 1uA of current on these pins, having a 10 to gnd or +Vcc will not affect the logic level. The 10k can be left in place, as this is usually considered good practice to tie logic pins to power rails in this manner.

**Comment by darraghbr** [comment]
While I don't disagree with you that having a 10K resistor won't hurt, the data sheet on page 4 states this. That was the basis for me making this issue.

![image](https://user-images.githubusercontent.com/31858409/101991600-ceb26400-3ca5-11eb-9c0e-0184e7c591c0.png)

**Comment by mechatroniks-git** [comment]
The "directly" comment here is certainly confusing. 

I found this:  [eval board](https://www.ti.com/lit/ug/slvua73/slvua73.pdf?ts=1607799198136&ref_url=https%253A%252F%252Fwww.ti.com%252Ftool%252FTCA9548AEVM), Here TI is using 10K to gnd/vcc.
![image](https://user-images.githubusercontent.com/57600622/101992512-c12ab900-3c68-11eb-839e-ca504b43c0bb.png)
