### ISSUE TITLE
Flow Meter display

### ISSUE THREAD

**Issue by Judoguy12** [tetrabiodistributed/project-tetra#6]
How should the display work?

Current thought: show flow in mmH2O/sec as a waveform, allow different waveforms to be shown on a central board or show each waveform on each patient line, depending on how boards are wired.

**Comment by Judoguy12** [comment]
Ventilators use the following units

- Pressure - cmH20
- Flow - L/min
- Volume - ml
- Respiratory rate - br/min

**Comment by fpdotmonkey** [comment]
This is explored in https://github.com/tetrabiodistributed/project-tetra-display
