### ISSUE TITLE
⇑ A-TET-001003-0 Pressure Manifold Explode

### ISSUE THREAD

**Issue by Burhan-Q** [tetrabiodistributed/project-tetra#71]
**Create exploded view:** A-TET-001003-0 Pressure Manifold
- [ ] Assigned _(specify assignees)_
- [ ] Work in Progress _(move card on Project Board)_
- [ ] Submit for Review _(assign reviewer, comment, & move on Project Board)_
- [ ] Working on Review changes _(comment w/ list of changes and date)_
- [ ] Review complete _(assigned reviewer comment with approved date)_

**Comment by mechatroniks-git** [comment]
Exploded view looks good
![image](https://user-images.githubusercontent.com/57600622/89677522-72c47280-d8a2-11ea-9792-7e4364ccaeea.png)
