### ISSUE TITLE
P-TET-000021 Shutoff valve Knob - Design Updates

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/project-tetra#97]
- [x]  Thin wall section can't print, needs to be cut back or thickend up. 
- [x]  Loose fit when mating to P-TET-000019
- [x]  Needs more clearance when mating to P-TET-000020
- [ ]  Consider DFAM tweaks
- [x]  Emboss part number to model

**Comment by cyunis** [comment]
Videos from 7/20 showing screw details mostly and modifications to improve fit:
(also see Issue #98 for more videos of part P-TET-000021 with P-TET-000019 fit)

[20200720_181008.mp4.zip](https://github.com/tetrabiodistributed/project-tetra/files/4963976/20200720_181008.mp4.zip)

**Comment by mechatroniks-git** [comment]
![image](https://user-images.githubusercontent.com/57600622/88309952-f20f4f00-ccc3-11ea-98a9-2a62de569d14.png)

**Comment by jgrano** [comment]
![image](https://user-images.githubusercontent.com/38054469/88349154-7ab1dd80-cd0c-11ea-8745-e470dcb75e98.png)
0.25mm spacing between the knob and the inner stub on part 20

**Comment by mmroden** [comment]
1 day + 2 days revisions

**Comment by jgrano** [comment]
@mechatroniks-git We're ready to have you print this.

**Comment by jgrano** [comment]
https://github.com/tetrabiodistributed/project-tetra/blob/master/02_Development/Prototype_release/Alpha/Parts_to_print/P-TET-000021-1.stl 
@mechatroniks-git

**Comment by mechatroniks-git** [comment]
Printing

**Comment by mechatroniks-git** [comment]
The knob appears to fit to P-TET-000019 Shutoff Valve Thru Body pretty well. Need to adjust P-TET-000020 to allow for clearance when spinning.
